In [1]:
import numpy as np 

path = '/workspace/code/logs/camera_calibration/calibration_results/IMG_2420_calibration.npz'

with np.load(path) as data:
    camera_matrix = data['camera_matrix']
    dist_coeffs = data['dist_coeffs']
    rvecs = data['rvecs']
    tvecs = data['tvecs']

In [3]:
print("Camera Matrix:\n", camera_matrix)
print("Distortion Coefficients:\n", dist_coeffs)

Camera Matrix:
 [[1.53905292e+03 0.00000000e+00 8.67619960e+02]
 [0.00000000e+00 1.54153123e+03 5.72745232e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[ 7.23957018e-01 -8.84588782e+00 -2.97548953e-02 -6.41384470e-02
   3.67318161e+01]]
